services:

    web:
        image: alphalom-service:latest
        ports:
            - "8080:8080"
        working_dir: /app
        command: python3 /app/run_fastapi.py
        environment:
            ENV: production
            PYTHONPATH: /app
            DATABASE_CONN_STR: ${DATABASE_CONN_STR}
            REDIS_HOST: ${REDIS_HOST}
            WEB_WORKERS: 3
        restart: always

    chat_app:
        image: alphalom-service:latest
        ports:
            - "8082:8000"
        working_dir: /app
        command: python3 /app/run_chat_app.py
        environment:
            ENV: production
            PYTHONPATH: /app
            DATABASE_CONN_STR: ${DATABASE_CONN_STR}
            REDIS_HOST: ${REDIS_HOST}
        restart: always

    scheduler:
        image: alphalom-service:latest
        working_dir: /app
        command: python3 /app/scheduler.py
        environment:
            ENV: production
            PYTHONPATH: /app
            DATABASE_CONN_STR: ${DATABASE_CONN_STR}
            REDIS_HOST: ${REDIS_HOST}
        restart: always

    job_server:
        image: alphalom-service:latest
        working_dir: /app
        command: python3 /app/job/job_server.py
        environment:
            ENV: production
            PYTHONPATH: /app
            DATABASE_CONN_STR: ${DATABASE_CONN_STR}
            REDIS_HOST: ${REDIS_HOST}
        restart: always

    news_server:
        image: alphalom-service:latest
        working_dir: /app
        command: python3 /app/job/news_server.py
        environment:
            ENV: production
            PYTHONPATH: /app
            DATABASE_CONN_STR: ${DATABASE_CONN_STR}
            REDIS_HOST: ${REDIS_HOST}
        restart: always

    log_comsumer:
        image: alphalom-service:latest
        working_dir: /app
        command: python3 /app/log_comsumer.py
        environment:
            ENV: production
            PYTHONPATH: /app
            DATABASE_CONN_STR: ${DATABASE_CONN_STR}
            REDIS_HOST: ${REDIS_HOST}
        restart: always
